[US-231] creer message li bao
thomasbouix/QuickChat pull request #9
Opened 2021-01-19 20:05 UTC by BaoHuiling

Les tests ici sont écrit totalement avec le database. Les tests basé sur le serveur seront donc écrit dans le US-16x.

2021-01-19 20:45 UTC, SamirIssd requested changes
Des fichiers du projet ont été supprimés, on ne peut donc pas merge cette branche.
Il faudrait aussi mettre les README dans le sous-dossier US_README avec le nom de l'US et les tests également dans le sous-dossier tests (comme présenté sur la branche Master).
Et si possible éviter les fichiers inutiles comme __pycache__ et .DS_Store pour garder un git propre =)

2021-01-19 20:50 UTC, BaoHuiling commented
> Des fichiers du projet ont été supprimés, on ne peut donc pas merge cette branche.
> Il faudrait aussi mettre les README dans le sous-dossier US_README avec le nom de l'US et les tests également dans le sous-dossier tests (comme présenté sur la branche Master).
> Et si possible éviter les fichiers inutiles comme **pycache** et .DS_Store pour garder un git propre =)

D'accord, je vais le réorganiser. Donc après je n'ai plus besoin de refaire le pull request?

2021-01-19 21:03 UTC, SamirIssd commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:70.85pt 70.85pt 70.85pt 70.85pt;}
div.WordSection1
	{page:WordSection1;}
-->Je ne sais pas si vous pourrez résoudre tous les problèmes sur cette branche mais si vous y arrivez normalement pas besoin de refaire la pull request la branche se mettra à jour toute seule.  De : BaoHuilingEnvoyé le :mardi 19 janvier 2021 21:50À : thomasbouix/QuickChatCc : SamirIssd; CommentObjet :Re: [thomasbouix/QuickChat] [US-231] creer message li bao (#9) Des fichiers du projet ont été supprimés, on ne peut donc pas merge cette branche.Il faudrait aussi mettre les README dans le sous-dossier US_README avec le nom de l'US et les tests également dans le sous-dossier tests (comme présenté sur la branche Master).Et si possible éviter les fichiers inutiles comme pycache et .DS_Store pour garder un git propre =)D'accord, je vais le réorganiser. Donc après je n'ai plus besoin de refaire le pull request?—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe. 

2021-01-19 22:01 UTC, BaoHuiling reviewed
[US-231] changes reviewed

2021-01-19 22:14 UTC, SamirIssd approved these changes

2021-01-20 14:49 UTC, TheoGermain commented
J'ai testé votre code, il semblerait qu'il y ait un petit problème d'import a cause du déplacement des tests dans un sous-dossier (qui peut être résolu en s'inspirant de la méthode des autres tests déjà existants). Pour l'import de la fonction `createDb` à la troisième ligne, il faut enlever la majuscule pour que cela fonctionne.
Pour le test de la fonction, il fonctionne très bien, je rajouterais juste un appel aux fonctions `deleteDb` et `createDb` comme cela à été fait dans d'autre tests, car cela permet d'exécuter le test de manière complètement indépendante même si la base de donnée n'a pas encore été créé.
Je pense que votre fonction `addMessage` pourrait être déplacé et intégrée au fichier `QuickChat_bdd.py` comme c'est une fonction de manipulation de la base de données, et que le test pourrait tout a fait s'intégrer dans `testBdd.py`.

2021-01-20 15:08 UTC, BaoHuiling commented
> J'ai testé votre code, il semblerait qu'il y ait un petit problème d'import a cause du déplacement des tests dans un sous-dossier (qui peut être résolu en s'inspirant de la méthode des autres tests déjà existants). Pour l'import de la fonction `createDb` à la troisième ligne, il faut enlever la majuscule pour que cela fonctionne.
> Pour le test de la fonction, il fonctionne très bien, je rajouterais juste un appel aux fonctions `deleteDb` et `createDb` comme cela à été fait dans d'autre tests, car cela permet d'exécuter le test de manière complètement indépendante même si la base de donnée n'a pas encore été créé.
> Je pense que votre fonction `addMessage` pourrait être déplacé et intégrée au fichier `QuickChat_bdd.py` comme c'est une fonction de manipulation de la base de données, et que le test pourrait tout a fait s'intégrer dans `testBdd.py`.

Merci! Je vais faire des améliorations ce soir.

2021-01-21 21:06 UTC, BaoHuiling commented
Nous avons fait des corriges dans le code. Aussi pour la brache US232. （￣▽￣）

2021-01-21 21:48 UTC, TheoGermain approved these changes

2021-01-21 21:48 UTC, merged